from langchain_core.tools import tool


@tool
def draft_legal_notice(
    sender_name: str,
    sender_address: str,
    recipient_name: str,
    recipient_address: str,
    subject: str,
    facts: str,
    legal_grounds: str,
    demand: str,
    compliance_days: int = 15,
) -> str:
    """Draft a legal notice based on the provided details.

    Args:
        sender_name: Full name of the sender (or 'Through Advocate [Name]').
        sender_address: Complete address of the sender.
        recipient_name: Full name of the recipient.
        recipient_address: Complete address of the recipient.
        subject: Subject line of the notice.
        facts: Key facts and background of the matter.
        legal_grounds: Legal provisions/sections under which the notice is sent.
        demand: Specific relief or demand sought.
        compliance_days: Number of days given for compliance (default 15).

    Returns:
        Formatted legal notice draft.
    """
    return f"""## LEGAL NOTICE

**Date**: [Insert Date]

**From:**
{sender_name}
{sender_address}

**To:**
{recipient_name}
{recipient_address}

**Subject: {subject}**

**NOTICE**

Under instructions from and on behalf of my client, {sender_name}, I hereby serve upon you \
the following Legal Notice:

### FACTS AND BACKGROUND

{facts}

### LEGAL GROUNDS

{legal_grounds}

### DEMAND

In light of the above facts and legal provisions, my client hereby calls upon you to:

{demand}

### COMPLIANCE

You are hereby called upon to comply with the above demand within **{compliance_days} days** \
from the date of receipt of this notice, failing which my client shall be constrained to \
initiate appropriate legal proceedings against you, civil and/or criminal, at your risk, \
cost and consequences, which please note.

This notice is issued without prejudice to any other rights and remedies available to my \
client under law.

---

**{sender_name}**
[Signature]

*Note: This is a draft generated by AI. Please have it reviewed by a qualified advocate before sending.*
"""


@tool
def draft_engagement_letter(
    firm_name: str,
    client_name: str,
    engagement_type: str,
    scope_of_work: str,
    fees: str,
    timeline: str,
    professional_type: str = "CA",
) -> str:
    """Draft a professional engagement letter for CA or Lawyer.

    Args:
        firm_name: Name of the CA firm or law firm.
        client_name: Name of the client (individual or company).
        engagement_type: Type of engagement (e.g., 'Tax Audit', 'Statutory Audit', 'Legal Advisory', 'ITR Filing').
        scope_of_work: Description of the scope of engagement.
        fees: Fee structure and payment terms.
        timeline: Timeline for completion of the engagement.
        professional_type: 'CA' for Chartered Accountant or 'Lawyer' for Advocate.

    Returns:
        Formatted engagement letter draft.
    """
    if professional_type == "CA":
        regulator = "Institute of Chartered Accountants of India (ICAI)"
        standards = "Standards on Auditing (SAs) and ICAI Guidelines"
    else:
        regulator = "Bar Council of India"
        standards = "Bar Council of India Rules and Advocates Act, 1961"

    return f"""## ENGAGEMENT LETTER

**Date**: [Insert Date]
**Ref No**: [Insert Reference Number]

**To:**
{client_name}
[Address]

**Subject: Engagement for {engagement_type}**

Dear Sir/Madam,

Thank you for engaging **{firm_name}** for the above-mentioned professional services. \
This letter sets out the terms and conditions of our engagement.

### 1. SCOPE OF ENGAGEMENT

{scope_of_work}

### 2. OUR RESPONSIBILITIES

We shall perform the engagement in accordance with the applicable {standards} issued by the \
{regulator}. Our services will be conducted with due professional care and in compliance \
with the applicable laws and regulations.

### 3. CLIENT'S RESPONSIBILITIES

You are responsible for:
- Providing complete and accurate information and documents in a timely manner
- Ensuring internal controls and compliance with applicable laws
- Designating a single point of contact for coordination
- Responding to queries within reasonable timelines

### 4. FEES AND PAYMENT TERMS

{fees}

GST @ 18% will be charged additionally on the professional fees as applicable.

### 5. TIMELINE

{timeline}

### 6. CONFIDENTIALITY

We shall maintain strict confidentiality of all information and documents shared with us \
during the course of this engagement, except as required by law or professional standards.

### 7. LIMITATION OF LIABILITY

Our liability under this engagement shall be limited to the fees received for this engagement. \
We shall not be liable for any consequential, indirect, or punitive damages.

### 8. INDEPENDENCE {"(For Audit Engagements)" if "audit" in engagement_type.lower() else ""}

{"We confirm that we are independent of the entity as required by the Code of Ethics issued by ICAI." if professional_type == "CA" and "audit" in engagement_type.lower() else ""}

### 9. TERMINATION

Either party may terminate this engagement by giving 30 days written notice. Fees for work \
completed up to the date of termination shall be payable.

### 10. DISPUTE RESOLUTION

Any disputes arising out of this engagement shall be resolved through arbitration under the \
Arbitration and Conciliation Act, 1996, with the seat of arbitration at [Insert City].

---

Please confirm your acceptance by signing and returning a copy of this letter.

**For {firm_name}**

[Name]
[Designation]
[Membership No. / Enrolment No.]

**Accepted and Agreed**

**For {client_name}**

[Authorized Signatory]
[Date]

*Note: This is a draft. Please review and customize before use.*
"""


@tool
def draft_board_resolution(
    company_name: str,
    cin: str,
    resolution_subject: str,
    resolution_text: str,
    meeting_date: str,
    directors_present: str,
) -> str:
    """Draft a board resolution for a company.

    Args:
        company_name: Name of the company.
        cin: Corporate Identity Number.
        resolution_subject: Subject of the resolution.
        resolution_text: Full text of the resolution to be passed.
        meeting_date: Date of the board meeting.
        directors_present: Comma-separated names of directors present.

    Returns:
        Formatted board resolution draft.
    """
    directors = [d.strip() for d in directors_present.split(",")]

    return f"""## BOARD RESOLUTION

**{company_name}**
CIN: {cin}
Registered Office: [Insert Address]

---

### MINUTES OF THE MEETING OF THE BOARD OF DIRECTORS

**Date**: {meeting_date}
**Time**: [Insert Time]
**Venue**: [Insert Venue / "Via Video Conferencing" as per MCA Circular]

**Directors Present:**
{chr(10).join(f"- {d}" for d in directors)}

**Quorum**: Present as required under Section 174 of the Companies Act, 2013.

**Chairperson**: {directors[0]} (Chairman of the meeting)

---

### RESOLUTION: {resolution_subject}

**RESOLVED THAT** {resolution_text}

**FURTHER RESOLVED THAT** the Board hereby authorizes any one Director or the Company \
Secretary of the Company to do all such acts, deeds, matters, and things as may be necessary, \
desirable, or expedient to give effect to the above resolution.

---

**Voting**: The resolution was passed unanimously by all Directors present.

**Sd/-**
{directors[0]}
Chairman of the Meeting

*Note: This is a draft. Please review and file as per Companies Act, 2013 requirements.*
"""


@tool
def draft_nda(
    disclosing_party: str,
    receiving_party: str,
    purpose: str,
    confidentiality_period_years: int = 3,
    jurisdiction: str = "Delhi",
) -> str:
    """Draft a Non-Disclosure Agreement (NDA).

    Args:
        disclosing_party: Name of the disclosing party.
        receiving_party: Name of the receiving party.
        purpose: Purpose of sharing confidential information.
        confidentiality_period_years: Duration of confidentiality obligation in years.
        jurisdiction: City/state for governing law and jurisdiction.

    Returns:
        Formatted NDA draft.
    """
    return f"""## NON-DISCLOSURE AGREEMENT

**This Non-Disclosure Agreement** ("Agreement") is entered into on [Insert Date] \
("Effective Date") by and between:

**1. {disclosing_party}** ("Disclosing Party"), having its registered office at [Address]; and

**2. {receiving_party}** ("Receiving Party"), having its registered office at [Address].

(Collectively referred to as "Parties" and individually as "Party")

### RECITALS

WHEREAS, the Disclosing Party possesses certain confidential and proprietary information; and

WHEREAS, the Receiving Party desires to receive such information for the purpose of \
{purpose} ("Purpose");

NOW THEREFORE, in consideration of the mutual covenants contained herein, the Parties agree as follows:

### 1. DEFINITION OF CONFIDENTIAL INFORMATION

"Confidential Information" means all information, whether written, oral, electronic, or visual, \
disclosed by the Disclosing Party to the Receiving Party, including but not limited to: \
trade secrets, business plans, financial information, client lists, technical data, software, \
designs, strategies, and any other proprietary information.

### 2. OBLIGATIONS OF THE RECEIVING PARTY

The Receiving Party shall:
(a) Hold all Confidential Information in strict confidence;
(b) Not disclose, publish, or disseminate Confidential Information to any third party;
(c) Use Confidential Information solely for the Purpose;
(d) Take reasonable measures to protect the confidentiality of the information;
(e) Limit disclosure to employees/agents who need to know, and ensure they are bound by similar obligations.

### 3. EXCLUSIONS

This Agreement does not apply to information that:
(a) Is or becomes publicly available through no fault of the Receiving Party;
(b) Was already known to the Receiving Party prior to disclosure;
(c) Is independently developed without reference to Confidential Information;
(d) Is received from a third party without breach of any obligation;
(e) Is required to be disclosed by law, regulation, or court order (with prior notice to Disclosing Party).

### 4. TERM

The confidentiality obligations under this Agreement shall survive for a period of \
**{confidentiality_period_years} years** from the date of disclosure.

### 5. RETURN OF INFORMATION

Upon termination or expiry of this Agreement, or upon request, the Receiving Party shall \
promptly return or destroy all Confidential Information and certify such return/destruction.

### 6. REMEDIES

The Parties acknowledge that breach of this Agreement may cause irreparable harm. The \
Disclosing Party shall be entitled to seek injunctive relief in addition to any other \
legal remedies available.

### 7. GOVERNING LAW AND JURISDICTION

This Agreement shall be governed by and construed in accordance with the laws of India. \
Any disputes shall be subject to the exclusive jurisdiction of the courts in **{jurisdiction}**.

### 8. GENERAL PROVISIONS

(a) This Agreement constitutes the entire agreement between the Parties regarding its subject matter.
(b) No amendment shall be effective unless in writing and signed by both Parties.
(c) Neither Party may assign this Agreement without prior written consent.

---

**IN WITNESS WHEREOF**, the Parties have executed this Agreement as of the Effective Date.

**For {disclosing_party}**
Name: _______________
Designation: _______________
Signature: _______________
Date: _______________

**For {receiving_party}**
Name: _______________
Designation: _______________
Signature: _______________
Date: _______________

*Note: This is a draft. Please have it reviewed by a qualified advocate before execution.*
"""


@tool
def draft_partnership_deed(
    firm_name: str,
    partner_names: str,
    business_nature: str,
    capital_contributions: str,
    profit_sharing_ratio: str,
    jurisdiction: str = "Delhi",
) -> str:
    """Draft a Partnership Deed under the Indian Partnership Act, 1932.

    Args:
        firm_name: Name of the partnership firm.
        partner_names: Comma-separated names of all partners.
        business_nature: Nature and scope of the business.
        capital_contributions: Comma-separated capital contribution by each partner (e.g., 'A:500000,B:300000').
        profit_sharing_ratio: Profit/loss sharing ratio (e.g., '60:40' or 'A:60,B:40').
        jurisdiction: City for jurisdiction clause.

    Returns:
        Formatted partnership deed draft.
    """
    partners = [p.strip() for p in partner_names.split(",")]

    return f"""## PARTNERSHIP DEED

**This Partnership Deed** is made and executed on [Insert Date] at {jurisdiction}, by and between:

{chr(10).join(f"**{i+1}. {p}**, S/o [Father's Name], R/o [Address] (hereinafter referred to as the '{chr(65+i)}th Partner')" for i, p in enumerate(partners))}

(Collectively referred to as "Partners")

### RECITALS

The Partners have agreed to carry on business in partnership under the provisions of the \
Indian Partnership Act, 1932, on the following terms and conditions:

### 1. NAME AND STYLE

The partnership firm shall be known as **"{firm_name}"**.

### 2. NATURE OF BUSINESS

{business_nature}

### 3. PLACE OF BUSINESS

The principal place of business shall be at [Insert Address], {jurisdiction}.

### 4. COMMENCEMENT AND DURATION

The partnership shall commence from [Insert Date] and shall continue until dissolved \
by mutual consent or as per the provisions of this deed.

### 5. CAPITAL CONTRIBUTION

{capital_contributions}

Interest on capital shall be allowed at the rate of 12% per annum (maximum allowable \
under Section 40(b) of the Income Tax Act, 1961).

### 6. PROFIT AND LOSS SHARING

The profits and losses of the firm shall be shared in the following ratio:
**{profit_sharing_ratio}**

### 7. REMUNERATION TO PARTNERS

Working partners shall be entitled to remuneration as per the limits prescribed under \
Section 40(b)(v) of the Income Tax Act, 1961:
- On first ₹3,00,000 of book profit or in case of loss: ₹1,50,000 or 90% of book profit, whichever is more
- On the balance: 60% of book profit

### 8. DRAWINGS

Each partner may draw up to ₹[amount] per month. Interest on drawings shall be charged \
at [rate]% per annum.

### 9. BANKING AND ACCOUNTS

- Bank accounts shall be operated jointly / by any partner [specify].
- Books of accounts shall be maintained at the principal place of business.
- Accounts shall be audited annually by a Chartered Accountant if required under Sec 44AB.
- Financial year: April 1 to March 31.

### 10. DUTIES AND OBLIGATIONS

Each partner shall:
- Devote full time and attention to the business (unless otherwise agreed)
- Not engage in any competing business
- Act in good faith and utmost fidelity towards the firm and co-partners

### 11. RETIREMENT AND EXPULSION

- A partner may retire by giving 3 months' written notice
- Outgoing partner's share shall be determined based on the last audited balance sheet
- Goodwill shall be valued at [method: average profits / super profits / capitalization]

### 12. DISSOLUTION

The firm shall be dissolved:
- By mutual consent of all partners
- On death or insolvency of a partner (unless continued by remaining partners)
- By court order under Section 44 of the Partnership Act, 1932

### 13. ARBITRATION

Any dispute shall be resolved by arbitration under the Arbitration and Conciliation Act, 1996. \
The seat of arbitration shall be {jurisdiction}.

### 14. TDS ON PARTNER REMUNERATION

As per Section 194T (effective FY 2025-26), TDS at 10% shall be deducted on remuneration, \
salary, commission, bonus, or interest paid to partners exceeding ₹20,000 in a financial year.

---

**IN WITNESS WHEREOF**, the Partners have signed this deed on the date first written above.

{chr(10).join(f"**{p}**{chr(10)}Signature: _______________{chr(10)}Date: _______________{chr(10)}" for p in partners)}

**Witnesses:**
1. Name: _______________ | Signature: _______________
2. Name: _______________ | Signature: _______________

*Note: Register this deed with the Registrar of Firms. This is a draft — please review \
with a qualified advocate. Stamp duty as per state law is applicable.*
"""


@tool
def draft_power_of_attorney(
    principal_name: str,
    attorney_name: str,
    purpose: str,
    powers: str,
    is_general: bool = False,
    jurisdiction: str = "Delhi",
) -> str:
    """Draft a Power of Attorney (General or Special) under the Powers of Attorney Act, 1882.

    Args:
        principal_name: Name of the person granting the power.
        attorney_name: Name of the person receiving the power (the attorney/agent).
        purpose: Purpose for which the power is being granted.
        powers: Comma-separated list of specific powers granted.
        is_general: True for General Power of Attorney (GPA), False for Special Power of Attorney (SPA).
        jurisdiction: City/state for jurisdiction.

    Returns:
        Formatted Power of Attorney draft.
    """
    poa_type = "GENERAL POWER OF ATTORNEY" if is_general else "SPECIAL POWER OF ATTORNEY"
    power_list = [p.strip() for p in powers.split(",")]

    return f"""## {poa_type}

(Under the Powers of Attorney Act, 1882)

**KNOW ALL MEN BY THESE PRESENTS** that I, **{principal_name}**, S/o [Father's Name], \
aged [Age] years, R/o [Address], {jurisdiction} (hereinafter called the "Principal/Executant") \
do hereby appoint and constitute:

**{attorney_name}**, S/o [Father's Name], aged [Age] years, R/o [Address], {jurisdiction} \
(hereinafter called the "Attorney/Agent")

as my true and lawful Attorney to act on my behalf for the following purpose(s):

### PURPOSE

{purpose}

### POWERS GRANTED

I hereby authorize my said Attorney to do and perform the following acts on my behalf:

{chr(10).join(f"{i+1}. {p}" for i, p in enumerate(power_list))}

{"### ADDITIONAL GENERAL POWERS" if is_general else ""}
{"The Attorney shall have full power and authority to do all such acts, deeds, and things as may be necessary or expedient, as fully and effectually as I could do if personally present." if is_general else ""}

### CONDITIONS AND LIMITATIONS

1. This Power of Attorney shall {"remain in force until revoked in writing" if is_general else "be valid only for the specific purpose mentioned above and shall stand revoked upon completion of the said purpose"}.
2. The Attorney shall act in good faith and in the best interest of the Principal.
3. The Attorney shall not delegate the powers conferred unless specifically authorized.
4. The Attorney shall maintain proper accounts of all transactions made on behalf of the Principal.
5. The Attorney shall not use the powers for personal benefit.

### INDEMNITY

I hereby agree to ratify and confirm all lawful acts done by the said Attorney in pursuance \
of this Power of Attorney.

### REVOCATION

This Power of Attorney may be revoked by the Principal at any time by giving written notice \
to the Attorney. {"" if is_general else "It shall automatically stand revoked upon completion of the specific purpose."}

### GOVERNING LAW

This Power of Attorney shall be governed by the laws of India, specifically the Powers of \
Attorney Act, 1882, and the Indian Contract Act, 1872.

---

**IN WITNESS WHEREOF**, I have executed this Power of Attorney on this [Day] day of [Month], [Year] \
at {jurisdiction}.

**EXECUTANT/PRINCIPAL**
{principal_name}
Signature: _______________

**ACCEPTED BY ATTORNEY**
{attorney_name}
Signature: _______________

**WITNESSES:**
1. Name: _______________ | Address: _______________ | Signature: _______________
2. Name: _______________ | Address: _______________ | Signature: _______________

**NOTARY PUBLIC** (if applicable)
[Notary Name & Seal]

---

### Important Notes:
- **Registration**: {"GPA for immovable property MUST be registered (as per SC ruling in Suraj Lamp v. State of Haryana, 2011)" if is_general else "SPA should be notarized; registration recommended for property matters"}
- **Stamp Duty**: Applicable as per state stamp duty laws
- **Validity**: {"GPA does not transfer ownership — it only authorizes the agent to act" if is_general else "Valid only for the specific purpose stated"}
- GPA **cannot** be used for sale of immovable property (to avoid stamp duty evasion)

*Note: This is a draft. Please review with a qualified advocate before execution and registration.*
"""


@tool
def draft_rent_agreement(
    landlord_name: str,
    tenant_name: str,
    property_address: str,
    monthly_rent: float,
    security_deposit: float,
    lease_period_months: int = 11,
    start_date: str = "[Insert Date]",
    jurisdiction: str = "Delhi",
) -> str:
    """Draft a Rent/Lease Agreement under the Transfer of Property Act, 1882.

    Args:
        landlord_name: Name of the landlord/lessor.
        tenant_name: Name of the tenant/lessee.
        property_address: Full address of the rented property.
        monthly_rent: Monthly rent amount (₹).
        security_deposit: Security deposit amount (₹).
        lease_period_months: Lease duration in months (default 11 — avoids mandatory registration).
        start_date: Start date of the lease.
        jurisdiction: City/state for jurisdiction and stamp duty.

    Returns:
        Formatted rent agreement draft.
    """
    annual_rent = monthly_rent * 12
    registration_note = ("**Note:** Lease > 11 months requires mandatory registration under "
                         "Section 17 of the Registration Act, 1908. Registration charges and "
                         "stamp duty will apply as per state laws.") if lease_period_months > 11 else ""

    return f"""## RENT / LEASE AGREEMENT

**This Rent Agreement** is made and executed on **{start_date}** at {jurisdiction}, between:

**LANDLORD / LESSOR:**
**{landlord_name}**, S/o [Father's Name], R/o [Address]
(Hereinafter referred to as the "Landlord", which expression shall include heirs, successors, and assigns)

**AND**

**TENANT / LESSEE:**
**{tenant_name}**, S/o [Father's Name], R/o [Address]
(Hereinafter referred to as the "Tenant", which expression shall include heirs, successors, and assigns)

### PROPERTY DETAILS

The Landlord hereby lets out the following property to the Tenant:

**Address:** {property_address}
**Type:** [Residential / Commercial]
**Area:** [Insert Area in sq. ft.]
**Furnishing:** [Furnished / Semi-Furnished / Unfurnished]

### TERMS AND CONDITIONS

**1. LEASE PERIOD**
The lease shall be for a period of **{lease_period_months} months**, commencing from **{start_date}**.
{registration_note}

**2. MONTHLY RENT**
₹{monthly_rent:,.0f} (Rupees [In Words] only) payable on or before the 5th of each month.

**3. RENT ESCALATION**
The rent shall be increased by **5-10%** on renewal, as mutually agreed.

**4. SECURITY DEPOSIT**
₹{security_deposit:,.0f} (Rupees [In Words] only), refundable at the time of vacating the property, \
after deducting any outstanding dues or damages.

**5. MAINTENANCE CHARGES**
[As applicable — specify who pays society maintenance, property tax, etc.]

**6. ELECTRICITY AND WATER**
The Tenant shall pay electricity and water charges as per meter reading / actual consumption.

**7. USE OF PROPERTY**
The Tenant shall use the property exclusively for [residential / commercial — specify] purposes \
and shall not use it for any illegal or immoral activities.

**8. SUBLETTING**
The Tenant shall NOT sublet, assign, or transfer the property or any part thereof to any third party.

**9. REPAIRS AND MAINTENANCE**
- **Landlord:** Major structural repairs, external painting, plumbing lines
- **Tenant:** Day-to-day maintenance, minor repairs, internal upkeep

**10. TERMINATION**
Either party may terminate this agreement by giving **2 months' written notice**. \
The Tenant shall hand over the property in its original condition (normal wear and tear excepted).

**11. LOCK-IN PERIOD**
[Insert duration, e.g., "The first 6 months shall be a lock-in period during which neither party can terminate."]

**12. INVENTORY LIST**
[Attach list of furniture, fittings, appliances provided with the property]

### TAX IMPLICATIONS

| Aspect | Details |
|--------|---------|
| TDS on Rent | Applicable u/s 194-IB if monthly rent > ₹50,000 (TDS @ 2%) |
| Income Tax | Rental income taxable under "Income from House Property" for landlord |
| GST | Applicable on commercial property rent (18%); Exempt for residential use |
| Stamp Duty | As per state laws (varies by state) |
| HRA Benefit | Tenant can claim HRA exemption u/s 10(13A) under Old Regime |

### DISPUTE RESOLUTION

Any dispute shall be first resolved through mutual discussion. Failing which, it shall be \
referred to arbitration under the Arbitration and Conciliation Act, 1996. \
Courts in **{jurisdiction}** shall have exclusive jurisdiction.

---

**IN WITNESS WHEREOF**, the parties have signed this agreement on the date first written above.

**LANDLORD**
{landlord_name}
Signature: _______________

**TENANT**
{tenant_name}
Signature: _______________

**WITNESSES:**
1. Name: _______________ | Signature: _______________
2. Name: _______________ | Signature: _______________

*Note: This is a draft. Stamp duty is payable as per state law. For lease > 11 months, \
registration under Registration Act, 1908 is mandatory. Please review with a qualified advocate.*
"""
