from langchain_core.tools import tool


@tool
def draft_legal_notice(
    sender_name: str,
    sender_address: str,
    recipient_name: str,
    recipient_address: str,
    subject: str,
    facts: str,
    legal_grounds: str,
    demand: str,
    compliance_days: int = 15,
) -> str:
    """Draft a legal notice based on the provided details.

    Args:
        sender_name: Full name of the sender (or 'Through Advocate [Name]').
        sender_address: Complete address of the sender.
        recipient_name: Full name of the recipient.
        recipient_address: Complete address of the recipient.
        subject: Subject line of the notice.
        facts: Key facts and background of the matter.
        legal_grounds: Legal provisions/sections under which the notice is sent.
        demand: Specific relief or demand sought.
        compliance_days: Number of days given for compliance (default 15).

    Returns:
        Formatted legal notice draft.
    """
    return f"""## LEGAL NOTICE

**Date**: [Insert Date]

**From:**
{sender_name}
{sender_address}

**To:**
{recipient_name}
{recipient_address}

**Subject: {subject}**

**NOTICE**

Under instructions from and on behalf of my client, {sender_name}, I hereby serve upon you \
the following Legal Notice:

### FACTS AND BACKGROUND

{facts}

### LEGAL GROUNDS

{legal_grounds}

### DEMAND

In light of the above facts and legal provisions, my client hereby calls upon you to:

{demand}

### COMPLIANCE

You are hereby called upon to comply with the above demand within **{compliance_days} days** \
from the date of receipt of this notice, failing which my client shall be constrained to \
initiate appropriate legal proceedings against you, civil and/or criminal, at your risk, \
cost and consequences, which please note.

This notice is issued without prejudice to any other rights and remedies available to my \
client under law.

---

**{sender_name}**
[Signature]

*Note: This is a draft generated by AI. Please have it reviewed by a qualified advocate before sending.*
"""


@tool
def draft_engagement_letter(
    firm_name: str,
    client_name: str,
    engagement_type: str,
    scope_of_work: str,
    fees: str,
    timeline: str,
    professional_type: str = "CA",
) -> str:
    """Draft a professional engagement letter for CA or Lawyer.

    Args:
        firm_name: Name of the CA firm or law firm.
        client_name: Name of the client (individual or company).
        engagement_type: Type of engagement (e.g., 'Tax Audit', 'Statutory Audit', 'Legal Advisory', 'ITR Filing').
        scope_of_work: Description of the scope of engagement.
        fees: Fee structure and payment terms.
        timeline: Timeline for completion of the engagement.
        professional_type: 'CA' for Chartered Accountant or 'Lawyer' for Advocate.

    Returns:
        Formatted engagement letter draft.
    """
    if professional_type == "CA":
        regulator = "Institute of Chartered Accountants of India (ICAI)"
        standards = "Standards on Auditing (SAs) and ICAI Guidelines"
    else:
        regulator = "Bar Council of India"
        standards = "Bar Council of India Rules and Advocates Act, 1961"

    return f"""## ENGAGEMENT LETTER

**Date**: [Insert Date]
**Ref No**: [Insert Reference Number]

**To:**
{client_name}
[Address]

**Subject: Engagement for {engagement_type}**

Dear Sir/Madam,

Thank you for engaging **{firm_name}** for the above-mentioned professional services. \
This letter sets out the terms and conditions of our engagement.

### 1. SCOPE OF ENGAGEMENT

{scope_of_work}

### 2. OUR RESPONSIBILITIES

We shall perform the engagement in accordance with the applicable {standards} issued by the \
{regulator}. Our services will be conducted with due professional care and in compliance \
with the applicable laws and regulations.

### 3. CLIENT'S RESPONSIBILITIES

You are responsible for:
- Providing complete and accurate information and documents in a timely manner
- Ensuring internal controls and compliance with applicable laws
- Designating a single point of contact for coordination
- Responding to queries within reasonable timelines

### 4. FEES AND PAYMENT TERMS

{fees}

GST @ 18% will be charged additionally on the professional fees as applicable.

### 5. TIMELINE

{timeline}

### 6. CONFIDENTIALITY

We shall maintain strict confidentiality of all information and documents shared with us \
during the course of this engagement, except as required by law or professional standards.

### 7. LIMITATION OF LIABILITY

Our liability under this engagement shall be limited to the fees received for this engagement. \
We shall not be liable for any consequential, indirect, or punitive damages.

### 8. INDEPENDENCE {"(For Audit Engagements)" if "audit" in engagement_type.lower() else ""}

{"We confirm that we are independent of the entity as required by the Code of Ethics issued by ICAI." if professional_type == "CA" and "audit" in engagement_type.lower() else ""}

### 9. TERMINATION

Either party may terminate this engagement by giving 30 days written notice. Fees for work \
completed up to the date of termination shall be payable.

### 10. DISPUTE RESOLUTION

Any disputes arising out of this engagement shall be resolved through arbitration under the \
Arbitration and Conciliation Act, 1996, with the seat of arbitration at [Insert City].

---

Please confirm your acceptance by signing and returning a copy of this letter.

**For {firm_name}**

[Name]
[Designation]
[Membership No. / Enrolment No.]

**Accepted and Agreed**

**For {client_name}**

[Authorized Signatory]
[Date]

*Note: This is a draft. Please review and customize before use.*
"""


@tool
def draft_board_resolution(
    company_name: str,
    cin: str,
    resolution_subject: str,
    resolution_text: str,
    meeting_date: str,
    directors_present: str,
) -> str:
    """Draft a board resolution for a company.

    Args:
        company_name: Name of the company.
        cin: Corporate Identity Number.
        resolution_subject: Subject of the resolution.
        resolution_text: Full text of the resolution to be passed.
        meeting_date: Date of the board meeting.
        directors_present: Comma-separated names of directors present.

    Returns:
        Formatted board resolution draft.
    """
    directors = [d.strip() for d in directors_present.split(",")]

    return f"""## BOARD RESOLUTION

**{company_name}**
CIN: {cin}
Registered Office: [Insert Address]

---

### MINUTES OF THE MEETING OF THE BOARD OF DIRECTORS

**Date**: {meeting_date}
**Time**: [Insert Time]
**Venue**: [Insert Venue / "Via Video Conferencing" as per MCA Circular]

**Directors Present:**
{chr(10).join(f"- {d}" for d in directors)}

**Quorum**: Present as required under Section 174 of the Companies Act, 2013.

**Chairperson**: {directors[0]} (Chairman of the meeting)

---

### RESOLUTION: {resolution_subject}

**RESOLVED THAT** {resolution_text}

**FURTHER RESOLVED THAT** the Board hereby authorizes any one Director or the Company \
Secretary of the Company to do all such acts, deeds, matters, and things as may be necessary, \
desirable, or expedient to give effect to the above resolution.

---

**Voting**: The resolution was passed unanimously by all Directors present.

**Sd/-**
{directors[0]}
Chairman of the Meeting

*Note: This is a draft. Please review and file as per Companies Act, 2013 requirements.*
"""


@tool
def draft_nda(
    disclosing_party: str,
    receiving_party: str,
    purpose: str,
    confidentiality_period_years: int = 3,
    jurisdiction: str = "Delhi",
) -> str:
    """Draft a Non-Disclosure Agreement (NDA).

    Args:
        disclosing_party: Name of the disclosing party.
        receiving_party: Name of the receiving party.
        purpose: Purpose of sharing confidential information.
        confidentiality_period_years: Duration of confidentiality obligation in years.
        jurisdiction: City/state for governing law and jurisdiction.

    Returns:
        Formatted NDA draft.
    """
    return f"""## NON-DISCLOSURE AGREEMENT

**This Non-Disclosure Agreement** ("Agreement") is entered into on [Insert Date] \
("Effective Date") by and between:

**1. {disclosing_party}** ("Disclosing Party"), having its registered office at [Address]; and

**2. {receiving_party}** ("Receiving Party"), having its registered office at [Address].

(Collectively referred to as "Parties" and individually as "Party")

### RECITALS

WHEREAS, the Disclosing Party possesses certain confidential and proprietary information; and

WHEREAS, the Receiving Party desires to receive such information for the purpose of \
{purpose} ("Purpose");

NOW THEREFORE, in consideration of the mutual covenants contained herein, the Parties agree as follows:

### 1. DEFINITION OF CONFIDENTIAL INFORMATION

"Confidential Information" means all information, whether written, oral, electronic, or visual, \
disclosed by the Disclosing Party to the Receiving Party, including but not limited to: \
trade secrets, business plans, financial information, client lists, technical data, software, \
designs, strategies, and any other proprietary information.

### 2. OBLIGATIONS OF THE RECEIVING PARTY

The Receiving Party shall:
(a) Hold all Confidential Information in strict confidence;
(b) Not disclose, publish, or disseminate Confidential Information to any third party;
(c) Use Confidential Information solely for the Purpose;
(d) Take reasonable measures to protect the confidentiality of the information;
(e) Limit disclosure to employees/agents who need to know, and ensure they are bound by similar obligations.

### 3. EXCLUSIONS

This Agreement does not apply to information that:
(a) Is or becomes publicly available through no fault of the Receiving Party;
(b) Was already known to the Receiving Party prior to disclosure;
(c) Is independently developed without reference to Confidential Information;
(d) Is received from a third party without breach of any obligation;
(e) Is required to be disclosed by law, regulation, or court order (with prior notice to Disclosing Party).

### 4. TERM

The confidentiality obligations under this Agreement shall survive for a period of \
**{confidentiality_period_years} years** from the date of disclosure.

### 5. RETURN OF INFORMATION

Upon termination or expiry of this Agreement, or upon request, the Receiving Party shall \
promptly return or destroy all Confidential Information and certify such return/destruction.

### 6. REMEDIES

The Parties acknowledge that breach of this Agreement may cause irreparable harm. The \
Disclosing Party shall be entitled to seek injunctive relief in addition to any other \
legal remedies available.

### 7. GOVERNING LAW AND JURISDICTION

This Agreement shall be governed by and construed in accordance with the laws of India. \
Any disputes shall be subject to the exclusive jurisdiction of the courts in **{jurisdiction}**.

### 8. GENERAL PROVISIONS

(a) This Agreement constitutes the entire agreement between the Parties regarding its subject matter.
(b) No amendment shall be effective unless in writing and signed by both Parties.
(c) Neither Party may assign this Agreement without prior written consent.

---

**IN WITNESS WHEREOF**, the Parties have executed this Agreement as of the Effective Date.

**For {disclosing_party}**
Name: _______________
Designation: _______________
Signature: _______________
Date: _______________

**For {receiving_party}**
Name: _______________
Designation: _______________
Signature: _______________
Date: _______________

*Note: This is a draft. Please have it reviewed by a qualified advocate before execution.*
"""
